### ISSUE TITLE
fix crash during sync

### ISSUE THREAD

**Issue by mmatiaschek** [Welthungerhilfe/cgm-scanner#36]
see Crashlytics Issue and Stacktrace below

steps to reproduce:

- start App (online)
- add manual measures
- wait a few minutes

**Comment by mmatiaschek** [comment]
https://console.firebase.google.com/u/0/project/child-growth-monitor-dev/crashlytics/app/android:de.welthungerhilfe.cgm.scanner/issues/5b1a524e6007d59fcd3cd8fd?time=last-seven-days&sessionId=5B282A31005C000115BE957C7F7E07D3_DNE_0_v2

**Comment by mmatiaschek** [comment]
```
06-18 00:23:11.739 15374-15374/de.welthungerhilfe.cgm.scanner D/MyUploadService: uploadFromUri: getDownloadUri success
06-18 00:23:11.748 15374-15374/de.welthungerhilfe.cgm.scanner D/MyBaseTaskService: changeNumberOfTasks:1:-1
    stopping
06-18 00:24:52.139 15374-15886/de.welthungerhilfe.cgm.scanner W/Firestore: (0.6.6-dev) [Firestore]: The behavior for java.util.Date objects stored in Firestore is going to change AND YOUR APP MAY BREAK.
    To hide this warning and ensure your app does not break, you need to add the following code to your app before calling any other Cloud Firestore methods:
    
    FirebaseFirestore firestore = FirebaseFirestore.getInstance();
    FirebaseFirestoreSettings settings = new FirebaseFirestoreSettings.Builder()
        .setTimestampsInSnapshotsEnabled(true)
        .build();
    firestore.setFirestoreSettings(settings);
    
    With this change, timestamps stored in Cloud Firestore will be read back as com.google.firebase.Timestamp objects instead of as system java.util.Date objects. So you will also need to update code expecting a java.util.Date to instead expect a Timestamp. For example:
    
    // Old:
    java.util.Date date = snapshot.getDate("created_at");
    // New:
    Timestamp timestamp = snapshot.getTimestamp("created_at");
    java.util.Date date = timestamp.toDate();
    
    Please audit all existing usages of java.util.Date when you enable the new behavior. In a future release, the behavior will be changed to the new behavior, so if you do not follow these steps, YOUR APP MAY BREAK.
06-18 00:24:52.142 15374-15374/de.welthungerhilfe.cgm.scanner W/Firestore: (0.6.6-dev) [Firestore]: The behavior for java.util.Date objects stored in Firestore is going to change AND YOUR APP MAY BREAK.
    To hide this warning and ensure your app does not break, you need to add the following code to your app before calling any other Cloud Firestore methods:
    
    FirebaseFirestore firestore = FirebaseFirestore.getInstance();
    FirebaseFirestoreSettings settings = new FirebaseFirestoreSettings.Builder()
        .setTimestampsInSnapshotsEnabled(true)
        .build();
    firestore.setFirestoreSettings(settings);
    
    With this change, timestamps stored in Cloud Firestore will be read back as com.google.firebase.Timestamp objects instead of as system java.util.Date objects. So you will also need to update code expecting a java.util.Date to instead expect a Timestamp. For example:
    
    // Old:
    java.util.Date date = snapshot.getDate("created_at");
    // New:
    Timestamp timestamp = snapshot.getTimestamp("created_at");
    java.util.Date date = timestamp.toDate();
    
    Please audit all existing usages of java.util.Date when you enable the new behavior. In a future release, the behavior will be changed to the new behavior, so if you do not follow these steps, YOUR APP MAY BREAK.
06-18 00:24:54.824 15374-15462/de.welthungerhilfe.cgm.scanner E/SQLiteLog: (5) database is locked
06-18 00:24:54.835 15374-15462/de.welthungerhilfe.cgm.scanner E/SQLiteDatabase: Failed to open database '/data/user/0/de.welthungerhilfe.cgm.scanner/databases/firestore.%5BDEFAULT%5D.child-growth-monitor-dev.%28default%29'.
    android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: PRAGMA journal_mode
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
        at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:632)
        at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:318)
        at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:292)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:213)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:191)
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
        at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:571)
        at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:269)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
        at com.google.firebase.firestore.c.zzat.zza(SourceFile:74)
        at com.google.firebase.firestore.b.zzf.zza(SourceFile:1214)
        at com.google.firebase.firestore.b.zzh.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at com.google.firebase.firestore.g.zza$zza.run(SourceFile:190)
        at java.lang.Thread.run(Thread.java:818)
06-18 00:24:54.836 15374-15374/de.welthungerhilfe.cgm.scanner D/AndroidRuntime: Shutting down VM
06-18 00:24:55.044 15374-15374/de.welthungerhilfe.cgm.scanner E/AndroidRuntime: FATAL EXCEPTION: main
    Process: de.welthungerhilfe.cgm.scanner, PID: 15374
    java.lang.RuntimeException: Internal error in Firestore (0.6.6-dev).
        at com.google.firebase.firestore.g.zza.zzb(SourceFile:324)
        at com.google.firebase.firestore.g.zzd.run(Unknown Source)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.app.ActivityThread.main(ActivityThread.java:5418)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
     Caused by: java.lang.RuntimeException: Failed to gain exclusive lock to the Firestore client's offline persistence. This generally means you are using Firestore from multiple processes in your app. Keep in mind that multi-process Android apps execute the code in your Application class in all processes, so you may need to avoid initializing Firestore in your Application class. If you are intentionally using Firestore from multiple processes, you can only enable offline persistence (i.e. call setPersistenceEnabled(true)) in one of them.
        at com.google.firebase.firestore.c.zzat.zza(SourceFile:77)
        at com.google.firebase.firestore.b.zzf.zza(SourceFile:1214)
        at com.google.firebase.firestore.b.zzh.run(Unknown Source)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at com.google.firebase.firestore.g.zza$zza.run(SourceFile:190)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: android.database.sqlite.SQLiteDatabaseLockedException: database is locked (code 5): , while compiling: PRAGMA journal_mode
        at android.database.sqlite.SQLiteConnection.nativePrepareStatement(Native Method)
        at android.database.sqlite.SQLiteConnection.acquirePreparedStatement(SQLiteConnection.java:887)
        at android.database.sqlite.SQLiteConnection.executeForString(SQLiteConnection.java:632)
        at android.database.sqlite.SQLiteConnection.setJournalMode(SQLiteConnection.java:318)
        at android.database.sqlite.SQLiteConnection.setWalModeFromConfiguration(SQLiteConnection.java:292)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:213)
        at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:191)
        at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
        at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
        at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:806)
        at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:791)
        at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:694)
        at android.app.ContextImpl.openOrCreateDatabase(ContextImpl.java:571)
        at android.content.ContextWrapper.openOrCreateDatabase(ContextWrapper.java:269)
        at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:223)
        at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
        at com.google.firebase.firestore.c.zzat.zza(SourceFile:74)
        at com.google.firebase.firestore.b.zzf.zza(SourceFile:1214) 
        at com.google.firebase.firestore.b.zzh.run(Unknown Source) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154) 
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
        at com.google.firebase.firestore.g.zza$zza.run(SourceFile:190) 
        at java.lang.Thread.run(Thread.java:818) 
06-18 00:24:55.048 15374-15889/de.welthungerhilfe.cgm.scanner D/FA: Logging event (FE): app_exception(_ae), Bundle[{firebase_event_origin(_o)=clx, _r=1, firebase_screen_class(_sc)=CreateDataActivity, firebase_screen_id(_si)=-4985997125202701826, timestamp=1529274294839, fatal=1}]
06-18 00:24:55.102 15374-15889/de.welthungerhilfe.cgm.scanner V/FA: Connecting to remote service
06-18 00:24:55.111 15374-15889/de.welthungerhilfe.cgm.scanner V/FA: Recording user engagement, ms: 160899
06-18 00:24:55.122 15374-15889/de.welthungerhilfe.cgm.scanner D/FA: Logging event (FE): user_engagement(_e), Bundle[{firebase_event_origin(_o)=auto, engagement_time_msec(_et)=160899, firebase_screen_class(_sc)=CreateDataActivity, firebase_screen_id(_si)=-4985997125202701826}]
06-18 00:24:55.152 15374-15889/de.welthungerhilfe.cgm.scanner V/FA: Connection attempt already in progress
06-18 00:24:55.808 15374-15448/de.welthungerhilfe.cgm.scanner I/CrashlyticsCore: Crashlytics report upload complete: 5B26DEFC014C-0001-3C0E-957C7F7E07D3
```
